notifications:
  email:
    on_success: never

sudo: false

language: node_js
node_js:
  - "7"

os:
  - osx
  - linux

cache:
  directories:
    - node_modules
    - .vscode-test
    - tools/prebuild-cache

env:
  - ELECTRON_RUN_AS_NODE=1

before_install:
  - rmdir .vscode-test || echo "[INFO] Using cached VSCode binary"
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - node --version
  - npm --version
  - npm run pretest
  - npm run vscode:prepublish

script:
  - npm run test:offline
  - ls -la .vscode-test || true
  - md5sum .vscode-test/VSCode-linux-x64/code || true
