notifications:
  email:
    on_success: never

sudo: false

language: node_js
node_js:
  - "7"

os:
  - osx
  - linux

cache:
  directories:
    - node_modules
    - .vscode-test
    - tools/prebuild-cache
  yarn: true

env:
  - ELECTRON_RUN_AS_NODE=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - node --version
  - npm --version
  - npm run pretest
  - npm run vscode:prepublish

before_script:
  - npm run --silent vscode-cache:latest

script:
  - npm run test:offline

before_cache:
  - npm run --silent vscode-cache:mark
