environment:
  ELECTRON_RUN_AS_NODE: 1

cache:
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 7.9.0 x64
  - npm install -g npm@4 --silent

test_script:
  - node --version
  - npm --version
  - npm test
