environment:
  ELECTRON_RUN_AS_NODE: 1

cache:
  - node_modules
  - .vscode-test
  - tools/prebuild-cache
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 7.9.0 x64
  - npm install -g npm@4 --silent
  - node --version
  - npm --version
  - npm run pretest
  - npm run vscode:prepublish

build_script:
  - npm run --silent vscode-cache:latest

test_script:
  - npm run test:offline

after_test:
  - npm run --silent vscode-cache:mark
